from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_EVOLUTION_PATH = Path(__file__).resolve().parents[1] / "EVOLUTION.md"
FEEDBACK_SECTION_HEADER = "## Feedback Updates"


def utc_day() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def build_entry(date: str, source: str, summary: str, actions: list[str], next_items: list[str]) -> str:
    action_lines = "\n".join(f"- {item}" for item in actions) if actions else "- None yet"
    next_lines = "\n".join(f"- {item}" for item in next_items) if next_items else "- None"

    return (
        f"### {date} — {source}\n"
        f"Summary: {summary}\n\n"
        "Actions taken:\n"
        f"{action_lines}\n\n"
        "Next loop targets:\n"
        f"{next_lines}\n\n"
    )


def ensure_feedback_section(doc_text: str) -> str:
    if FEEDBACK_SECTION_HEADER in doc_text:
        return doc_text

    suffix = "\n" if doc_text.endswith("\n") else "\n\n"
    return f"{doc_text}{suffix}{FEEDBACK_SECTION_HEADER}\n\n"


def append_feedback(path: Path, entry: str) -> str:
    original = path.read_text(encoding="utf-8")
    with_section = ensure_feedback_section(original)
    updated = f"{with_section}{entry}"
    return updated


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Append a structured feedback loop update to EVOLUTION.md",
    )
    parser.add_argument("--source", required=True, help="Feedback source (example: Grok 4.20 Beta)")
    parser.add_argument("--summary", required=True, help="One-line summary of the feedback")
    parser.add_argument(
        "--actions",
        action="append",
        default=[],
        help="Action implemented from the feedback (repeat for multiple)",
    )
    parser.add_argument(
        "--next",
        dest="next_items",
        action="append",
        default=[],
        help="Next candidate step generated by this feedback (repeat for multiple)",
    )
    parser.add_argument("--date", default=utc_day(), help="Date label in YYYY-MM-DD format")
    parser.add_argument(
        "--file",
        default=str(DEFAULT_EVOLUTION_PATH),
        help="Path to EVOLUTION.md (defaults to repository EVOLUTION.md)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print output instead of writing file")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    evolution_path = Path(args.file)

    if not evolution_path.exists():
        raise FileNotFoundError(f"Could not find evolution file: {evolution_path}")

    new_entry = build_entry(
        date=args.date,
        source=args.source,
        summary=args.summary,
        actions=args.actions,
        next_items=args.next_items,
    )
    updated_text = append_feedback(evolution_path, new_entry)

    if args.dry_run:
        print(new_entry)
        return

    evolution_path.write_text(updated_text, encoding="utf-8")
    print(f"Appended feedback update to {evolution_path}")


if __name__ == "__main__":
    main()
